database:
  default: # 数据源名称,当不指定数据源时 default 为默认数据源
    type: "mysql" # 数据库类型
    host: "mysql" # 数据库地址
    port: "3306" # 数据库端口
    user: "root" # 数据库用户名
    pass: "123456" # 数据库密码
    name: "cool" # 数据库名称
    charset: "utf8mb4" # 数据库编码
    timezone: "Asia/Shanghai" # 数据库时区
    # debug: true # 是否开启调试模式，开启后会打印SQL日志
    createdAt: "createTime" # 创建时间字段
    updatedAt: "updateTime" # 更新时间字段

redis:
  cool:
    address: "redis:6379"
    db: 0

cool:
  autoMigrate: true
  eps: true
  file:
    mode: "local"
    domain: "http://127.0.0.1:38300"

modules:
  base:
    jwt:
      sso: false
      secret: "chatgpt-share-server"
      token:
        expire: 7200 # 2*3600
        refreshExpire: 1296000 # 24*3600*15
    middleware:
      authority:
        enable: 1
      log:
        enable: 1

# 注册用户免费体验时间，单位小时
FREE_TIER: 1

# 推广佣金比例
COMMISSION_RATE: 0.15

# 最低提现金额
ALLOWED_WITHDRAWAL: 40

# 文件服务器地址，以 / 结尾。用于存放用户上传的收款码，此域名的根目录为docker-compose.yml 对应文件映射的目录
# 比如- /www/wwwroot/img.xxx:/root/share/images/ 那FILE_SERVER的根目录就是/www/wwwroot/img.xxx
FILE_SERVER: "https://xxx/"

# 发卡地址。配置后，在用户兑换页（未登陆），用户选车页，用户聊天页都可以跳转发卡地址
FAKA_URL: "https://xxx/"

# 邮箱配置，必须配置，否则用户无法注册，无法重置密码
MAIL_FROM: "" # 发件人邮箱
MAIL_PASS: "" # 邮箱密码，一般不是登陆密码
MAIL_HOST: "smtp.gmail.com" # 邮箱服务器地址
MAIL_PORT: "587" # 邮箱服务器端口
# 注册邮箱白名单。清空: 关闭白名单 有值: 开启白名单
MAIL_WHITELIST: "@gmail.com,@yahoo.com,@hotmail.com,@outlook.com,@icloud.com,@163.com,@126.com,@qq.com,@foxmail.com"
SITE_NAME: "" #站点名称，用于发送邮件的友好提示
