services:
  mysql:
    image: mysql:8.4.5
    command: --mysql-native-password=ON --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --binlog-expire-logs-seconds=2592
    restart: always
    container_name: share-mysql
    volumes:
      - ./data/mysql/:/var/lib/mysql/
      - ./docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/
    environment:
      TZ: Asia/Shanghai # 指定时区
      MYSQL_ROOT_PASSWORD: "123456" # 配置root用户密码
      MYSQL_DATABASE: "cool" # 业务库名
      MYSQL_USER: "cool" # 业务库用户名
      MYSQL_PASSWORD: "123123" # 业务库密码

  redis:
    image: redis
    # command: --requirepass "12345678" # redis库密码,不需要密码注释本行
    restart: always
    container_name: share-redis
    environment:
      TZ: Asia/Shanghai # 指定时区
    volumes:
      - ./data/redis/:/data/
    command: redis-server --appendonly yes

  gpt-share-server:
    image: jurieo/gpt-share-server:undefined #商业版标签是undefined
    restart: always
    container_name: share-main
    ports:
      - 127.0.0.1:38300:8001
    environment:
      TZ: Asia/Shanghai # 指定时区
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config.yaml:/app/config.yaml
      - ./data/chatgpt-share-server/:/app/data/
      - ./data/chatgpt-share-server/logs/:/app/logs/
      - ./data/chatgpt-share-server/images:/app/resource/public/images/
      - ./data/chatgpt-share-server/images:/app/public/uploads
      - ./data/keywords.txt:/app/data/keywords.txt # 关键词文件，每行一个。自定义的时候打开此行
      - ./data/claudeExtend.js:/app/resource/public/claudeExtend.js # 在claude页需额外执行的脚本
      - ./data/chatgptExtend.js:/app/resource/public/chatgptExtend.js # 在chatgpt页需额外执行的脚本
      - ./data/midjourneyExtend.js:/app/resource/public/midjourney/midjourneyExtend.js # 在mj页需额外执行的脚本
      - ./data/grokExtend.js:/app/resource/public/grok/grokExtend.js # 在grok页需额外执行的脚本
      # 如需其他映射，请在此后继续添加。

    labels:
      - "com.centurylinklabs.watchtower.scope=jurieo-chatgpt-share-web"
    depends_on:
      - mysql
      - redis

  watchtower:
    # image: ghcr.io/nicholas-fedor/watchtower:latest
    image: nickfedor/watchtower #两者都行
    container_name: share-watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --scope jurieo-chatgpt-share-web --cleanup --interval 600
    restart: always
    environment:
      - TZ=Asia/Shanghai
    labels:
      - "com.centurylinklabs.watchtower.scope=jurieo-chatgpt-share-web"

  # 管理mysql，非必要不开启
  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - "18080:8080"
